exports.PermissionType = {
    ADD_PERMISSION: "ADD_PERMISSION",
    DELETE_PERMISSION: "DELETE_PERMISSION",
    GET_PERMISSION: "GET_PERMISSION",
    CREATE_PUB: "CREATE_PUB",
    DELETE_PUB: "DELETE_PUB",
    GET_PUB: "GET_PUB",
    CHANGE_INFORMATION: "CHANGE_INFORMATION",
    DELETE_USER: "DELETE_USER",
    GET_USER_INFORMATION: "GET_USER_INFORMATION",
    ADD_CONTACT: "ADD_CONTACT",
    DELETE_CONTACT: "DELETE_CONTACT",
    GET_CONTACT: "GET_CONTACT",
    CREATE_IMO: "CREATE_IMO",
    DELETE_IMO: "DELETE_IMO",
    GET_IMO: "GET_IMO"
} 

exports.ResponseType = {
    SUCCESS: "SUCCESS",
    MISMATCH_FIELD: "MISMATCH_FIELD",
    USER_EXIST: "USER_EXIST",
    PASSWORD_ERROR: "PASSWORD_ERROR",
    USER_NOT_EXIST: "USER_NOT_EXIST",
    TMP_ERROR: "TMP_ERROR",
    PERMISSION_ERROR: "PERMISSION_ERROR",
    ERROR: "ERROR",
    TOKEN_MISSING: "TOKEN MISSING",
    NOT_IMG: "NOT_IMG"
}